### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by fizolas** [artem78/LmxConverter#1]
Hi Artem,

I just discovered this interesting repository of yours. A couple of questions:

- I see the program is in Pascal, which means that it should be compiled. How should one do that? Maybe a compilation Makefile would be handy, to make this straightforward.
- Do you plan to implement  conversion from kml/gpx to lmx as well? It would be useful to be able to pass landmarks created in the computer to the phone.

Cheers.

**Comment by artem78** [comment]
Hi Fizolas.

> I see the program is in Pascal, which means that it should be compiled. How should one do that?

Yes, this tool was written in Free Pascal. You can compile it with [Lazarus IDE](https://www.lazarus-ide.org/). Furthermore you can download built executable from [Releases](https://github.com/artem78/LmxConverter/releases) page.

> Do you plan to implement conversion from kml/gpx to lmx as well?

It's possible. Maybe in the future..

**Comment by artem78** [comment]
Added download link to ReadMe file.

**Comment by artem78** [comment]
> conversion from kml/gpx to lmx

You may try this: https://www.poieditor.com/poi_convert/kml-to-lmx/

**Comment by fizolas** [comment]
Brilliant, thank you Artem.

**Comment by artem78** [comment]
> Do you plan to implement  conversion from kml/gpx to lmx as well?

Added in [version 1.3](https://github.com/artem78/LmxConverter/releases/tag/v1.3).
